/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccountType = { 'client' : null } |
  { 'worker' : null };
export interface Booking {
  'id' : bigint,
  'status' : BookingStatus,
  'client' : Principal,
  'jobDetails' : string,
  'worker' : Principal,
  'dateTime' : string,
  'location' : string,
}
export type BookingStatus = { 'requested' : null } |
  { 'cancelled' : null } |
  { 'completed' : null } |
  { 'accepted' : null } |
  { 'declined' : null };
export interface NewBooking {
  'jobDetails' : string,
  'worker' : Principal,
  'dateTime' : string,
  'location' : string,
}
export interface PartialWorkerProfile {
  'serviceArea' : string,
  'displayName' : string,
  'hourlyRate' : bigint,
  'description' : string,
  'isActive' : boolean,
  'category' : ServiceCategory,
}
export type ServiceCategory = { 'cleaning' : null } |
  { 'other' : string } |
  { 'plumbing' : null } |
  { 'gardening' : null } |
  { 'electrical' : null };
export interface UserProfile {
  'name' : string,
  'accountType' : [] | [AccountType],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkerProfile {
  'serviceArea' : string,
  'displayName' : string,
  'owner' : Principal,
  'hourlyRate' : bigint,
  'description' : string,
  'isActive' : boolean,
  'category' : ServiceCategory,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'browseWorkers' : ActorMethod<[], Array<WorkerProfile>>,
  'browseWorkersByCategory' : ActorMethod<
    [ServiceCategory],
    Array<WorkerProfile>
  >,
  'browseWorkersByRateAscending' : ActorMethod<[], Array<WorkerProfile>>,
  'browseWorkersByRateDescending' : ActorMethod<[], Array<WorkerProfile>>,
  'createBookingRequest' : ActorMethod<[NewBooking], bigint>,
  'createWorkerProfile' : ActorMethod<[PartialWorkerProfile], undefined>,
  'getBooking' : ActorMethod<[bigint], Booking>,
  'getBookingsByClient' : ActorMethod<[Principal], Array<Booking>>,
  'getBookingsByStatus' : ActorMethod<[BookingStatus], Array<Booking>>,
  'getBookingsByWorker' : ActorMethod<[Principal], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkerProfile' : ActorMethod<[Principal], [] | [WorkerProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], undefined>,
  'updateWorkerProfile' : ActorMethod<[PartialWorkerProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];