/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ServiceCategory = IDL.Variant({
  'cleaning' : IDL.Null,
  'other' : IDL.Text,
  'plumbing' : IDL.Null,
  'gardening' : IDL.Null,
  'electrical' : IDL.Null,
});
export const WorkerProfile = IDL.Record({
  'serviceArea' : IDL.Text,
  'displayName' : IDL.Text,
  'owner' : IDL.Principal,
  'hourlyRate' : IDL.Nat,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'category' : ServiceCategory,
});
export const NewBooking = IDL.Record({
  'jobDetails' : IDL.Text,
  'worker' : IDL.Principal,
  'dateTime' : IDL.Text,
  'location' : IDL.Text,
});
export const PartialWorkerProfile = IDL.Record({
  'serviceArea' : IDL.Text,
  'displayName' : IDL.Text,
  'hourlyRate' : IDL.Nat,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'category' : ServiceCategory,
});
export const BookingStatus = IDL.Variant({
  'requested' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
  'accepted' : IDL.Null,
  'declined' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'client' : IDL.Principal,
  'jobDetails' : IDL.Text,
  'worker' : IDL.Principal,
  'dateTime' : IDL.Text,
  'location' : IDL.Text,
});
export const AccountType = IDL.Variant({
  'client' : IDL.Null,
  'worker' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'accountType' : IDL.Opt(AccountType),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'browseWorkers' : IDL.Func([], [IDL.Vec(WorkerProfile)], ['query']),
  'browseWorkersByCategory' : IDL.Func(
      [ServiceCategory],
      [IDL.Vec(WorkerProfile)],
      ['query'],
    ),
  'browseWorkersByRateAscending' : IDL.Func(
      [],
      [IDL.Vec(WorkerProfile)],
      ['query'],
    ),
  'browseWorkersByRateDescending' : IDL.Func(
      [],
      [IDL.Vec(WorkerProfile)],
      ['query'],
    ),
  'createBookingRequest' : IDL.Func([NewBooking], [IDL.Nat], []),
  'createWorkerProfile' : IDL.Func([PartialWorkerProfile], [], []),
  'getBooking' : IDL.Func([IDL.Nat], [Booking], ['query']),
  'getBookingsByClient' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getBookingsByStatus' : IDL.Func(
      [BookingStatus],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getBookingsByWorker' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkerProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(WorkerProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
  'updateWorkerProfile' : IDL.Func([PartialWorkerProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ServiceCategory = IDL.Variant({
    'cleaning' : IDL.Null,
    'other' : IDL.Text,
    'plumbing' : IDL.Null,
    'gardening' : IDL.Null,
    'electrical' : IDL.Null,
  });
  const WorkerProfile = IDL.Record({
    'serviceArea' : IDL.Text,
    'displayName' : IDL.Text,
    'owner' : IDL.Principal,
    'hourlyRate' : IDL.Nat,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'category' : ServiceCategory,
  });
  const NewBooking = IDL.Record({
    'jobDetails' : IDL.Text,
    'worker' : IDL.Principal,
    'dateTime' : IDL.Text,
    'location' : IDL.Text,
  });
  const PartialWorkerProfile = IDL.Record({
    'serviceArea' : IDL.Text,
    'displayName' : IDL.Text,
    'hourlyRate' : IDL.Nat,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'category' : ServiceCategory,
  });
  const BookingStatus = IDL.Variant({
    'requested' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
    'accepted' : IDL.Null,
    'declined' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'client' : IDL.Principal,
    'jobDetails' : IDL.Text,
    'worker' : IDL.Principal,
    'dateTime' : IDL.Text,
    'location' : IDL.Text,
  });
  const AccountType = IDL.Variant({ 'client' : IDL.Null, 'worker' : IDL.Null });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'accountType' : IDL.Opt(AccountType),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'browseWorkers' : IDL.Func([], [IDL.Vec(WorkerProfile)], ['query']),
    'browseWorkersByCategory' : IDL.Func(
        [ServiceCategory],
        [IDL.Vec(WorkerProfile)],
        ['query'],
      ),
    'browseWorkersByRateAscending' : IDL.Func(
        [],
        [IDL.Vec(WorkerProfile)],
        ['query'],
      ),
    'browseWorkersByRateDescending' : IDL.Func(
        [],
        [IDL.Vec(WorkerProfile)],
        ['query'],
      ),
    'createBookingRequest' : IDL.Func([NewBooking], [IDL.Nat], []),
    'createWorkerProfile' : IDL.Func([PartialWorkerProfile], [], []),
    'getBooking' : IDL.Func([IDL.Nat], [Booking], ['query']),
    'getBookingsByClient' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getBookingsByStatus' : IDL.Func(
        [BookingStatus],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getBookingsByWorker' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkerProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(WorkerProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
    'updateWorkerProfile' : IDL.Func([PartialWorkerProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };