/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface NewBooking {
    jobDetails: string;
    worker: Principal;
    dateTime: string;
    location: string;
}
export type ServiceCategory = {
    __kind__: "cleaning";
    cleaning: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "plumbing";
    plumbing: null;
} | {
    __kind__: "gardening";
    gardening: null;
} | {
    __kind__: "electrical";
    electrical: null;
};
export interface WorkerProfile {
    serviceArea: string;
    displayName: string;
    owner: Principal;
    hourlyRate: bigint;
    description: string;
    isActive: boolean;
    category: ServiceCategory;
}
export interface Booking {
    id: bigint;
    status: BookingStatus;
    client: Principal;
    jobDetails: string;
    worker: Principal;
    dateTime: string;
    location: string;
}
export interface UserProfile {
    name: string;
    accountType?: AccountType;
}
export interface PartialWorkerProfile {
    serviceArea: string;
    displayName: string;
    hourlyRate: bigint;
    description: string;
    isActive: boolean;
    category: ServiceCategory;
}
export enum AccountType {
    client = "client",
    worker = "worker"
}
export enum BookingStatus {
    requested = "requested",
    cancelled = "cancelled",
    completed = "completed",
    accepted = "accepted",
    declined = "declined"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    browseWorkers(): Promise<Array<WorkerProfile>>;
    browseWorkersByCategory(category: ServiceCategory): Promise<Array<WorkerProfile>>;
    browseWorkersByRateAscending(): Promise<Array<WorkerProfile>>;
    browseWorkersByRateDescending(): Promise<Array<WorkerProfile>>;
    createBookingRequest(newBooking: NewBooking): Promise<bigint>;
    createWorkerProfile(profile: PartialWorkerProfile): Promise<void>;
    getBooking(bookingId: bigint): Promise<Booking>;
    getBookingsByClient(client: Principal): Promise<Array<Booking>>;
    getBookingsByStatus(status: BookingStatus): Promise<Array<Booking>>;
    getBookingsByWorker(worker: Principal): Promise<Array<Booking>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWorkerProfile(worker: Principal): Promise<WorkerProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateBookingStatus(bookingId: bigint, newStatus: BookingStatus): Promise<void>;
    updateWorkerProfile(profile: PartialWorkerProfile): Promise<void>;
}
import type { AccountType as _AccountType, Booking as _Booking, BookingStatus as _BookingStatus, PartialWorkerProfile as _PartialWorkerProfile, ServiceCategory as _ServiceCategory, UserProfile as _UserProfile, UserRole as _UserRole, WorkerProfile as _WorkerProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async browseWorkers(): Promise<Array<WorkerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.browseWorkers();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.browseWorkers();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async browseWorkersByCategory(arg0: ServiceCategory): Promise<Array<WorkerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.browseWorkersByCategory(to_candid_ServiceCategory_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.browseWorkersByCategory(to_candid_ServiceCategory_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async browseWorkersByRateAscending(): Promise<Array<WorkerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.browseWorkersByRateAscending();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.browseWorkersByRateAscending();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async browseWorkersByRateDescending(): Promise<Array<WorkerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.browseWorkersByRateDescending();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.browseWorkersByRateDescending();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createBookingRequest(arg0: NewBooking): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createBookingRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBookingRequest(arg0);
            return result;
        }
    }
    async createWorkerProfile(arg0: PartialWorkerProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createWorkerProfile(to_candid_PartialWorkerProfile_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWorkerProfile(to_candid_PartialWorkerProfile_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getBooking(arg0: bigint): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_Booking_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_Booking_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByClient(arg0: Principal): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByClient(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByClient(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByStatus(arg0: BookingStatus): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByStatus(to_candid_BookingStatus_n17(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByStatus(to_candid_BookingStatus_n17(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByWorker(arg0: Principal): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByWorker(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByWorker(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkerProfile(arg0: Principal): Promise<WorkerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkerProfile(arg0);
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkerProfile(arg0);
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateBookingStatus(arg0: bigint, arg1: BookingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_BookingStatus_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateWorkerProfile(arg0: PartialWorkerProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkerProfile(to_candid_PartialWorkerProfile_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkerProfile(to_candid_PartialWorkerProfile_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AccountType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccountType): AccountType {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_BookingStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceCategory_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceCategory): ServiceCategory {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_WorkerProfile_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkerProfile): WorkerProfile {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AccountType]): AccountType | null {
    return value.length === 0 ? null : from_candid_AccountType_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WorkerProfile]): WorkerProfile | null {
    return value.length === 0 ? null : from_candid_WorkerProfile_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BookingStatus;
    client: Principal;
    jobDetails: string;
    worker: Principal;
    dateTime: string;
    location: string;
}): {
    id: bigint;
    status: BookingStatus;
    client: Principal;
    jobDetails: string;
    worker: Principal;
    dateTime: string;
    location: string;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n14(_uploadFile, _downloadFile, value.status),
        client: value.client,
        jobDetails: value.jobDetails,
        worker: value.worker,
        dateTime: value.dateTime,
        location: value.location
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    accountType: [] | [_AccountType];
}): {
    name: string;
    accountType?: AccountType;
} {
    return {
        name: value.name,
        accountType: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.accountType))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    serviceArea: string;
    displayName: string;
    owner: Principal;
    hourlyRate: bigint;
    description: string;
    isActive: boolean;
    category: _ServiceCategory;
}): {
    serviceArea: string;
    displayName: string;
    owner: Principal;
    hourlyRate: bigint;
    description: string;
    isActive: boolean;
    category: ServiceCategory;
} {
    return {
        serviceArea: value.serviceArea,
        displayName: value.displayName,
        owner: value.owner,
        hourlyRate: value.hourlyRate,
        description: value.description,
        isActive: value.isActive,
        category: from_candid_ServiceCategory_n6(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    requested: null;
} | {
    cancelled: null;
} | {
    completed: null;
} | {
    accepted: null;
} | {
    declined: null;
}): BookingStatus {
    return "requested" in value ? BookingStatus.requested : "cancelled" in value ? BookingStatus.cancelled : "completed" in value ? BookingStatus.completed : "accepted" in value ? BookingStatus.accepted : "declined" in value ? BookingStatus.declined : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    client: null;
} | {
    worker: null;
}): AccountType {
    return "client" in value ? AccountType.client : "worker" in value ? AccountType.worker : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cleaning: null;
} | {
    other: string;
} | {
    plumbing: null;
} | {
    gardening: null;
} | {
    electrical: null;
}): {
    __kind__: "cleaning";
    cleaning: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "plumbing";
    plumbing: null;
} | {
    __kind__: "gardening";
    gardening: null;
} | {
    __kind__: "electrical";
    electrical: null;
} {
    return "cleaning" in value ? {
        __kind__: "cleaning",
        cleaning: value.cleaning
    } : "other" in value ? {
        __kind__: "other",
        other: value.other
    } : "plumbing" in value ? {
        __kind__: "plumbing",
        plumbing: value.plumbing
    } : "gardening" in value ? {
        __kind__: "gardening",
        gardening: value.gardening
    } : "electrical" in value ? {
        __kind__: "electrical",
        electrical: value.electrical
    } : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkerProfile>): Array<WorkerProfile> {
    return value.map((x)=>from_candid_WorkerProfile_n4(_uploadFile, _downloadFile, x));
}
function to_candid_AccountType_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountType): _AccountType {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_BookingStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_PartialWorkerProfile_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PartialWorkerProfile): _PartialWorkerProfile {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceCategory_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceCategory): _ServiceCategory {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    serviceArea: string;
    displayName: string;
    hourlyRate: bigint;
    description: string;
    isActive: boolean;
    category: ServiceCategory;
}): {
    serviceArea: string;
    displayName: string;
    hourlyRate: bigint;
    description: string;
    isActive: boolean;
    category: _ServiceCategory;
} {
    return {
        serviceArea: value.serviceArea,
        displayName: value.displayName,
        hourlyRate: value.hourlyRate,
        description: value.description,
        isActive: value.isActive,
        category: to_candid_ServiceCategory_n8(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    accountType?: AccountType;
}): {
    name: string;
    accountType: [] | [_AccountType];
} {
    return {
        name: value.name,
        accountType: value.accountType ? candid_some(to_candid_AccountType_n30(_uploadFile, _downloadFile, value.accountType)) : candid_none()
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    requested: null;
} | {
    cancelled: null;
} | {
    completed: null;
} | {
    accepted: null;
} | {
    declined: null;
} {
    return value == BookingStatus.requested ? {
        requested: null
    } : value == BookingStatus.cancelled ? {
        cancelled: null
    } : value == BookingStatus.completed ? {
        completed: null
    } : value == BookingStatus.accepted ? {
        accepted: null
    } : value == BookingStatus.declined ? {
        declined: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountType): {
    client: null;
} | {
    worker: null;
} {
    return value == AccountType.client ? {
        client: null
    } : value == AccountType.worker ? {
        worker: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "cleaning";
    cleaning: null;
} | {
    __kind__: "other";
    other: string;
} | {
    __kind__: "plumbing";
    plumbing: null;
} | {
    __kind__: "gardening";
    gardening: null;
} | {
    __kind__: "electrical";
    electrical: null;
}): {
    cleaning: null;
} | {
    other: string;
} | {
    plumbing: null;
} | {
    gardening: null;
} | {
    electrical: null;
} {
    return value.__kind__ === "cleaning" ? {
        cleaning: value.cleaning
    } : value.__kind__ === "other" ? {
        other: value.other
    } : value.__kind__ === "plumbing" ? {
        plumbing: value.plumbing
    } : value.__kind__ === "gardening" ? {
        gardening: value.gardening
    } : value.__kind__ === "electrical" ? {
        electrical: value.electrical
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
